# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOKERHUB_SECRET_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.output.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-gh-actions
      - name: Verify
        run: echo ${{steps.docker_build.outputs.digest}}


  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Use Node.js ${{ matrix.node-version }}
      #  uses: actions/setup-node@v1
      #  with:
      #    node-version: ${{ matrix.node-version }}


      #- run: node index.js
      #- run: npm ci
      #- run: npm run build --if-present
      #- run: npm test
